apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: srt-clarity-search
  namespace: srt-clarity-search
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod-dns01"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - clarity.lab.hq.solidrust.net
    secretName: srt-clarity-search-tls
  rules:
  - host: clarity.lab.hq.solidrust.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: srt-clarity-search
            port:
              number: 80
